export const errorMessage = {
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  INVALID_TOKEN: 'INVALID_TOKEN',
  INVALID_TOKEN_SUBJECT: 'INVALID_TOKEN_SUBJECT',
  USER_RETRIEVAL_FAILURE: 'USER_RETRIEVAL_FAILURE',
  USER_ALREADY_EXIST: 'USER_ALREADY_EXIST',
  USER_CREATION_FAILURE: 'USER_CREATION_FAILURE'
};
