export const errorMessage = {
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  INVALID_TOKEN: 'INVALID_TOKEN',
  INVALID_TOKEN_SUBJECT: 'INVALID_TOKEN_SUBJECT',
  USER_RETRIEVAL_FAILURE: 'USER_RETRIEVAL_FAILURE',
  USER_ALREADY_EXIST: 'USER_ALREADY_EXIST',
  USER_CREATION_FAILURE: 'USER_CREATION_FAILURE',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  USER_UPDATE_FAILURE: 'USER_UPDATE_FAILURE',
  MISSING_AUTHORIZATION_HEADER: 'MISSING_AUTHORIZATION_HEADER',
  MISSING_AUTHORIZATION_HEADER_VALUE: 'MISSING_AUTHORIZATION_HEADER_VALUE',
  INVALID_AUTHORIZATION_PREFIX: 'INVALID_AUTHORIZATION_PREFIX',
  INVALID_USER_TOKEN: 'INVALID_USER_TOKEN'
};
