const errorMessage = {
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  INVALID_TOKEN: 'INVALID_TOKEN',
  INVALID_TOKEN_SUBJECT: 'INVALID_TOKEN_SUBJECT'
};

export default errorMessage;
